// copilot: completely generated by copilot.
const fs = require('node:fs');
const path = require('node:path');

const functionsDir = path.join(__dirname, '../functions');
const outputFile = path.join(functionsDir, 'index.js');
const ignoreFiles = ['index.js', 'template.js'];

try {
  const files = fs.readdirSync(functionsDir)
    .filter(file => file.endsWith('.js') && !ignoreFiles.includes(file));

  const content = files.map(file => {
    const name = path.basename(file, '.js');
    return `export { default as ${name} } from './${file}';`;
  }).join('\n');

  fs.writeFileSync(outputFile, content);
  console.log('generated functions/index.js');
} catch (error) {
  console.error('Error generating index:', error);
  process.exit(1);
}
