// copilot: completely generated by copilot.

const fs = require('node:fs');
const path = require('node:path');

const scriptsDir = path.join(__dirname, '../scripts');
const outputFile = path.join(scriptsDir, 'index.js');

try {
  const files = fs.readdirSync(scriptsDir)
    .filter(file => file.endsWith('.js') && file !== 'index.js');

  const content = files.map(file => {
    const name = path.basename(file, '.js');
    return `export * as ${name} from './${file}';`;
  }).join('\n');

  fs.writeFileSync(outputFile, content);
  console.log('generated scripts/index.js');
} catch (error) {
  console.error('Error generating index:', error);
  process.exit(1);
}
